# Regression Example in TensorFlow (with TensorBoard)
Predicting house prices in Boston, Massachusetts while logging results for TensorBoard

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/regression_in_tensorflow_with_tensorboard.ipynb)

#### Load dependencies

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint 
from tensorflow.keras.callbacks import TensorBoard # new!  
import os 

#### Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

57344/57026 [==============================] - 0s 0us/step


In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### Design neural network architecture

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                448       
_________________________________________________________________
batch_normalization (BatchNo (None, 32)                128       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_1 (Batch (None, 16)                64        
_________________________________________________________________
dropout (Dropout)            (None, 16)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_____________________________________________________

#### Configure Model

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
                                  save_weights_only=True) # otherwise full model is saved

In [14]:
tensorboard = TensorBoard(log_dir='logs/' + run_name)

#### Train!

In [15]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint, tensorboard]) 

Train on 404 samples, validate on 102 samples
Epoch 1/32
404/404 [==============================] - 1s 2ms/sample - loss: 578.5278 - val_loss: 467.7360
Epoch 2/32
404/404 [==============================] - 0s 172us/sample - loss: 552.8455 - val_loss: 493.0400
Epoch 3/32
404/404 [==============================] - 0s 173us/sample - loss: 535.2686 - val_loss: 482.7903
Epoch 4/32
404/404 [==============================] - 0s 172us/sample - loss: 514.6359 - val_loss: 471.4748
Epoch 5/32
404/404 [==============================] - 0s 170us/sample - loss: 489.1425 - val_loss: 479.5288
Epoch 6/32
404/404 [==============================] - 0s 171us/sample - loss: 462.1175 - val_loss: 507.7568
Epoch 7/32
404/404 [==============================] - 0s 170us/sample - loss: 428.6640 - val_loss: 493.8386
Epoch 8/32
404/404 [==============================] - 0s 176us/sample - loss: 398.7583 - val_loss: 475.0217
Epoch 9/32
404/404 [==============================] - 0s 176us/sample - loss: 356.6370 - val

#### Performing inference

In [16]:
model.load_weights(output_path + '/weights.28.hdf5')

In [17]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [18]:
y_valid[42]

14.1

In [19]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[14.502753]], dtype=float32)

# To start tensorboard... 
`tensorboard --logdir='logs/' --port 6006`
https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks
